# This docker compose file provides a Postgres database for use with Capone,
# configured with the same environment variables as the Capone application.
# Usage: docker-compose up -d

version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: capone-postgres
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - capone-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  capone-postgres-data:
